### ISSUE TITLE
Discussion about post-commit hooks

### ISSUE THREAD

**Issue by ghost** [daeken/Benjen#5]
Hey, saw this on HN and thought I'd write a few things down in case I fork this some time this week.
- If you have a post commit hook, it can potentially commit the changed markdown entries, build the site, then push the static files to a gh-pages branch somewhere, which would be cool.
- Would you then clean the static files, or should they be committed to? I can see arguments for both, but the markdown files are probably your best reference

**Comment by daeken** [comment]
I would definitely clean and push the static files each time, just in case they change.  I just put up an example post-receive hook in the readme, which is how I'm dealing with it on my side -- just a simple git hook on my server that pulls the latest content and runs benjen to put the output in the proper place.

If you come up with alternative ways of doing this, let me know and I'll throw it in the readme (or do so yourself and send a pull request) -- I figure there are many different use cases here.

**Comment by ghost** [comment]
A git submodule pointed to a gh-pages branch works. Now if only I knew how to use submodules...
