### ISSUE TITLE
Crash if you supply a command line argument

### ISSUE THREAD

**Issue by ghost** [daeken/Benjen#8]
$ benjen voltagex.org/

```
Traceback (most recent call last):
  File "/usr/local/bin/benjen", line 9, in <module>
    load_entry_point('Benjen==1.0', 'console_scripts', 'benjen')()
  File "/usr/local/lib/python2.7/dist-packages/Benjen-1.0-py2.7.egg/EGG-INFO/scripts/benjen.py", line 88, in main
    Benjen(*sys.argv[1:])
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by xraymemory** [comment]
The reason this is happening is that, obviously, Benjen.**init**() takes only one argument. To fix it, I have added some if-conditions such that if a directory is specified, all the file operations are changed to take place on that path whereas if no directory is specified (i.e. no command-line argument to benjen) then it will work in the current directory. It should be noted that when you give benjen a directory, it should be in the same format as specified in the README.
